### ISSUE TITLE
В чем может быть ошибка

### ISSUE THREAD

**Issue by burov0798** [olnaz/vkbot#1]
http://prntscr.com/9pbccy
Хотел запустить на машине https://koding.com да вылазит вот такая ошибка(

**Comment by olnaz** [comment]
Обнови Node.js на сервере до версии 5.x.x
Или используй флаг `--harmony` при запуске приложения

**Comment by burov0798** [comment]
Возможно где то с вами пообщаться кроме github? Ибо тут не слишком удобно

**Comment by burov0798** [comment]
Вроде бы все уже установил, запускаю, и - http://prntscr.com/9pk54w

**Comment by olnaz** [comment]
В файле config.js нужно указать рабочий токен с всеми permissions для бота. 

О токене: https://vk.com/dev/auth_mobile
О разрешениях: https://vk.com/dev/permissions

Метод из `node-vkapi`, который получает токен по логину и паролю (необходимо указать нужные разрешения, scope; читайте документацию): https://github.com/olnaz/node-vkapi#vkapigettokenbyloginparams

Написать мне можно во ВКонтакте: vk.com/olnaz
